name: Deploy main
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build

      # Share artifact inside workflow
      - uses: actions/upload-artifact@v3
        with:
          name: eb-artifact
          path: www/Archive.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Checkout source code
      uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: eb-artifact
        path: www

    - name: Display structure of downloaded files
      run: ls -R

    # https://github.com/marketplace/actions/beanstalk-deploy
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ImageFilterTahina
        environment_name: ImageFilterTahina-Environment
        version_label: 12345
        region: us-east-2
        deployment_package: ./www/Archive.zip
